
// USER  
export const USER_SIGNIN_API = 'USER_SIGNIN_API';
export const USLOGIN = 'USLOGIN';

export const GET_USER_SEARCH = 'GET_USER_SEARCH';
export const ADD_USER_PROJECT = 'ADD_USER_PROJECT';
export const REMOVE_USER_PROJECT = 'REMOVE_USER_PROJECT';
export const GET_USER_BY_PROJECT = 'GET_USER_BY_PROJECT';
export const GET_USER_BY_PROJECT_SAGA = 'GET_USER_BY_PROJECT_SAGA';
//GET ALL PROJECT CATEGORY

export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA';
export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY';

// CREATE PROJECT SAGA
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';

// GET ALL PROJECT SAGA
export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA';
export const GET_LIST_PROJECT = 'GET_LIST_PROJECT';
// UPDATE PROJECT SAGA
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
// DELETE PROJECT SAGA
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';
// GET_USER_API
export const GET_USER_API = 'GET_USER_API';
//GET DETAIL PROJECT
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';
//GET ALL PROJECT
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';